<h1>PHP Authentication</h1>
<p>Please log in with your username and password below.</p>
<form action="?" method="POST">
<label for="username">Username:</label>
	<input type="text" name="username" id="username" maxlength="20" size="20" /><br/>
<label for="password">Password:</label>
	<input type="password" name="password" id="password" maxlength=
	20" size="20" /><br/>
<input type="submit" />
</form>